### ISSUE TITLE
Add a "Build your own authentication strategy" section

### ISSUE THREAD

**Issue by gr2m** [octokit/authentication-strategies.js#4]
see https://github.com/octokit/auth-token.js for reference. The more important bit is the `auth.hook()` method as it can be directly passed as `options.request.hook` to [`@octokit/request`](https://github.com/octokit/request.js/#readme) and all the Octokit libraries based on it.

Not sure what people would build as I _think_ I covered all necessary authentication methods, but who knows :)

**Comment by HeroicHitesh** [comment]
@gr2m I am not sure what needs to be done here, but as far as I can understand we need to add this [`auth.hook()`](https://github.com/octokit/auth-token.js#authhookrequest-route-optionsorauthhookrequest-options) to `auth.js` repo's `README`.
Also I am not sure if we need to simply provide a link to navigate there or copy-paste that content here or create content similar to that here.

**Comment by gr2m** [comment]
An authentication strategy is a single function. The passed options are the strategy options, which differ from strategy to strategy. The strategy function returns a function that we refer to as `auth()`. The options passed to `auth()` are referred to as authentication options, they also differ from strategy to strategy. The `auth()` is asynchronous. Lastly, the `auth()` function must have an `auth.hook` property property which is an asynchronous function which is called with either `(request, route, options)` or `(request, options)`, compare https://github.com/octokit/request.js/#request

Does that all make sense?

**Comment by HeroicHitesh** [comment]
@gr2m I read through the READMEs of these 2 repos and got a bit of understanding about what you said. I think "Community Strategies" are strategies developed by community under "Build your own authentication strategy" scheme. So, what is needed to be done here? Do we need to create a section called "Build your own authentication strategy" with steps on how it can be created or is there something else?

**Comment by gr2m** [comment]
> Do we need to create a section called "Build your own authentication strategy" with steps on how it can be created

That's it 👍🏼

**Comment by gr2m** [comment]
we do have one now 🎉 https://github.com/octokit/authentication-strategies.js#create-your-own-octokit-authentication-strategy-module
